<?php
/*
 * Developer: Rene Voorberg
 * Team site: http://cmsideas.net/
 * Support: http://support.cmsideas.net/
 * 
 *
*/
 
?>

<div style="margin:20px;">
    <p class="switcher a-right" style="padding:5px 10px;"><?php echo $this->__('Select Range') ?>:
	 <select name="period" id="report_<?php echo $this->getHtmlId() ?>_period" onchange="changeDiagramsPeriod(this);">
        <?php foreach ($this->helper('adminhtml/dashboard_data')->getDatePeriods() as $_value=>$_label): ?>
            <?php if(in_array($_value, array('custom'))) continue; ?>
            <option value="<?php echo $_value ?>" <?php if($this->getRequest()->getParam('period')==$_value): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
        <?php endforeach; ?>
    </select></p><br/>
	 <?php
    $_containerStyle = "width:{$this->_width}px;height:{$this->_height}px; margin:0 auto; margin-top:20px";
	//$_containerStyle = "width:700px;height:500px; margin:0 auto;";
    ?>
    <?php 
	if($this->getCount()): 
		?>
    <p style="<?php echo $_containerStyle?>"><img src="<?php echo $this->getChartUrl(false) ?>" alt="chart" title="chart" /></p>
	<div class="customer-reward-point-graph-comment" style="margin-top:20px; text-align:center">
        <?php echo $this->getCommentContent();?>
    </div>
    <?php else: 
		?>
    <p class="a-center" style="<?php echo $_containerStyle?>"><?php echo $this->__('No Data Found') ?></p>
    <?php endif; ?>
</div>
