<?php $_order = $this->getOrder(); ?> 
<div class="product">        
    <!-- View Items-->
    <div class="grid np">
        <div class="hor-scroll table-responsive">
            <table cellspacing="0" class="table data order-tables">
                <col />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <col width="1" /> 
                <col width="1" /> 
                <thead>
                    <tr class="theadings">
                        <th><?php echo $this->helper('webpos')->__('Product') ?></th>
                        <th><?php echo $this->helper('webpos')->__('SKU') ?></th>
                        <th><?php echo $this->helper('webpos')->__('Price') ?></th>
                         <th width="20%"><?php echo $this->helper('webpos')->__('Return to Stock') ?></th>
                        <th class="a-center"><?php echo $this->helper('webpos')->__('Qty') ?></th>
                        <th class="last"><span class="nobr"><?php echo $this->helper('webpos')->__('Subtotal') ?></span></th>	
                    </tr>
                </thead>
                <?php $_items = $_order->getItemsCollection() ?>
                <?php
                $i = 0;
                foreach ($_items as $_item):
                if($_item->getQtyOrdered() > $_item->getQtyRefunded()):
                ?>	
                    <?php $baseSubTotal = Mage::app()->getStore()->formatPrice($_item->getData('qty_ordered') / 1 * $_item->getData('price') / 1); ?>
                    <?php $original_price = Mage::app()->getStore()->formatPrice($_item->getData('original_price')); ?>						
                    <?php $price = Mage::helper('core')->currency($_item->getData('base_price')); ?>
                    <?php $tax_amount = Mage::app()->getStore()->formatPrice($_item->getData('tax_amount')); ?>						
                    <?php $discount_amount = Mage::app()->getStore()->formatPrice($_item->getData('discount_amount')); ?>						
                    <?php $row_total =Mage::helper('core')->currency($_item->getData('base_row_total')); ?>
                    <?php $tax_percent = $_item->getData('tax_percent') . '%';
							$itemPrice = $_item->getPriceInclTax();
							$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
							$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
							$itemPrice = Mage::helper('directory')->currencyConvert($itemPrice, $baseCurrencyCode, $currentCurrencyCode);
							$row_total = Mage::app()->getStore()->formatPrice($itemPrice * ($_item->getQtyInvoiced() - $_item->getQtyRefunded()));
					?>						
                    <?php
                    if ($_item->getParentItem())
                        continue;
                    else
                        $i++;
                    ?>
                    <tbody class="<?php echo $i % 2 ? 'even' : 'odd' ?>">
                        <tr class="<?php echo ($i % 2) ? 'fist even' : ' last odd' ?>">
                            <td><?php echo $_item->getData('name') ?></td>
                            <td><?php echo $_item->getData('sku') ?></td>
                            <td><?php echo $price ?></td>
                            <td><input class="return_to_stock" name="return_to_stock" type="checkbox" id="return_to_stock_<?php echo $_item->getId(); ?>"/></td>
                            <td width="30px"><input type="text" class="qty_refund form-control" id="qty_refund_<?php echo $_item->getId(); ?>" value="<?php echo number_format($_item->getQtyOrdered() - $_item->getQtyRefunded(),0) ?>"/></td>					                                
                            <td><?php echo $row_total ?></td>							
                        </tr>						
                    </tbody>
                <?php endif; endforeach; ?>
            </table>
        </div>
    </div>
</div> 
<input id="order_id_wp" type="hidden" value = ""/>
<input id="invoice_id_wp" type="hidden" value = ""/>