<?php
/**
 * Mageplaza_BetterBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Post list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 *
 *
 * ===================================================================================
 *   INCLUDE THIS EXTENSION TO YOUR THEMES, PLEASE CONTACT ME AT harrytpps@gmail.com
 * ===================================================================================
 *
 *
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_posts = $this->getPosts(); ?>
<div class="page-title">
    <?php if (Mage::helper('mageplaza_betterblog/post')->isRssEnabled()) : ?>
        <div class="betterblog-rss">
            <a href="<?php echo Mage::helper('mageplaza_betterblog/post')->getRssUrl(); ?>" class="bb-rss-icon"><img
                    src="<?php echo $this->getSkinUrl('images/mageplaza_betterblog/rss.png') ?>" width="16px"/> </a>
        </div>
    <?php endif; ?>
</div>
<?php if ($_posts->getSize() > 0) : ?>
    <?php //echo $this->getPagerHtml(); ?>
    <div class="post-list-container">
        <?php foreach ($_posts as $_post) : ?>
            <div class="post-list-item">

                <div class="post-image">
                    <?php if ($_post->getImage()) : ?>
                        <a href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $_post->getPostTitle(); ?>">
                            <img
                                src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image'); ?>"
                                alt="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>"/>
                        </a>
                    <?php endif; ?>
                </div>


                <h2 class="mc-post-title">
                    <a href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $_post->getPostTitle(); ?>
                    </a>
                </h2>


                <div class="mc-post-info">
                    <i class=" icon-bubbles4 blog-meta-item"></i>
                    <span class="post-category blog-meta-item"><?php echo $this->__('In'); ?> <span class="dotted"><?php echo $_post->getPostCategoryHtml(); ?></span></span>
                    <span class="post-date blog-meta-item"><?php echo Mage::helper('core')->formatDate($_post->getCreatedAt(), 'medium', false) ?></span>
                    <?php if(Mage::helper('mageplaza_betterblog')->canShowCommentCount()): ?>
                        <span class="post-comments blog-meta-item dotted">
                            <?php echo Mage::helper('mageplaza_betterblog')->formatCommentCount($_post->getCommentCount()) . $this->__(' Comments'); ?>
                        </span>
                    <?php endif; ?>
                </div>


                <div class="post-short-description">
                    <?php echo $_post->getPostExcerpt(); ?><?php echo $this->__('...'); ?>
                </div>

                <div class="mc-clearfix"></div>


                <div class="mc-post-meta-info">
                    <div class="actions">
                        <a class="mc-read-more" href="<?php echo $_post->getPostUrl(); ?>"
                           title="<?php echo $this->__('Continue Reading'); ?>"><?php echo $this->__('Continue Reading'); ?></a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <div class="post-list-container">
        <?php echo Mage::helper('mageplaza_betterblog')->__('There are no posts at this moment'); ?>
    </div>
<?php endif; ?>
