<div class="wk-loading-mask">
	<div class="wk-loader"></div>
</div>
<?php
    /** @var Webkul_Preorder_Helper_Data $helper */
	$helper =  Mage::helper("preorder");
	$_product = $this->getProduct();
?>
<script>
	jQuery.noConflict();
	(function(jQuery){
		jQuery(".super-attribute-select").change(function(event){
			jQuery(".wk-loading-mask").show();
			jQuery(".wk-preorder-message-block").remove();
			var attributeArray = [];
			flag = 0;
			jQuery(".super-attribute-select").each(function(){
				var val = jQuery(this).find("option:selected").val();
				var id = jQuery(this).attr("id");
				id = id.split("attribute");
				attrId = id[1];
				result = attrId+"~"+val;
				attributeArray.push(result);
				if(val=="" || val==0) {
					flag=1;
				}
			});

			if(flag!=1) {
				jQuery.ajax({
					url: "<?php echo Mage::getUrl('preorder/index/checkPreOrder');?>",
					type: "POST",
					data: {product_id:<?php echo $_product->getId()?>,value:attributeArray},
					dataType: 'json',
					success:function(data){
						var status = data.preorder;
						if(status==1) {
							var html = data.msg;
							jQuery('.product-info-custom-text').before(html);
                            jQuery('.btn-cart').first().text('Preorder');
						} else {
							jQuery(".preorder-config-status").remove();
							jQuery('.btn-cart').first().text("Add to Cart");
						}
						jQuery(".wk-loading-mask").hide();
					}
				});
			} else {
				jQuery(".wk-loading-mask").hide();
			}
		});
	})(jQuery);
</script>