<?php
	$_product = $this->getProduct();
	/** @var Webkul_Preorder_Helper_Data $helper */
	$helper = Mage::helper("preorder");
	$typeArray = array('bundle','grouped');
	$result="";
?>
<?php if($helper->isPreorder($_product->getId())): ?>
	<?php
		$result="<div class='wk-preorder-message-block'>";
		$availability = $_product->getWkAvailability();
		if($availability!="") {
			$date = date_create($availability);
			$flag = 1;
		} else {
			$flag = 0;
		}
	?>
	
	<?php $result.= Mage::helper('preorder')->getPayPreorderHtml($_product) ?>
	<?php $result.= Mage::helper('preorder')->getPreorderCustomMessageHtml(); ?>
	<?php if($flag==1): ?>
		<?php
			$result.="<div class='wk-info'>";
			$result.= $this->__('Available on').": ".date_format($date, "l jS F Y");
			$result.="</div>";
		?>
	<?php endif; ?>
	<?php $result.= Mage::helper('preorder')->getAdditionalMessage($_product->getId()); ?>
	<?php $result.= "</div>"; ?>
<?php endif;?>
<script>
	jQuery.noConflict();
	(function(jQuery){
		var temp=<?php echo json_encode($result)?>;
		if(typeof(temp)!="undefined" && temp!="" && temp!=null){
			jQuery('.product-info-custom-text').before(temp);
			jQuery('.btn-cart').first().text('Preorder');
		}
	})(jQuery);
</script>
