<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
    $_baseUrl = Mage::getBaseUrl();
    $_currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $_relativeUrl = str_replace($_baseUrl, '/', $_currentUrl);
?>
<?php
    $_description = $_product->getDescription();
    $_attributes = new Mage_Catalog_Block_Product_View_Attributes();
    $_attributes->setProduct($_product->getId());
    $_additional = $_attributes->getAdditionalData();
    $_reviews = false;


$showImage = array(
    'KRO93847283',
    'KRO93847266',
    'KRO827778182993',
    'KRO36264777283',
    'KR046765754754',
);
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<section role="main" itemtype="http://schema.org/Product" itemscope>
    <div class="row product-view">
        <meta content="<?php echo $_relativeUrl; ?>" itemprop="url">
        <!-- Product Pic & Info -->
        <div class="small-12 product-essential columns">
            <div class="row">

                <?php if ($_product->getData('tradein_enable')
                             && Mage::getStoreConfig('magedevgroup_tradein/general/module_enable')) {
                          echo $this->getChildHtml('tradein_form');
                      }
                ?>

                <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

                    <?php echo $this->getBlockHtml('formkey') ?>
                    <div class="no-display">
                        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                        <input type="hidden" name="related_product" id="related-products-field" value="" />
                    </div>
                    <!-- First Column: Product Image -->
                    <?php echo $this->getChildHtml('media') ?>
                    <!-- Central Column: Product info -->
                    <div class="small-12 medium-8 product-shop columns">
                        <?php echo $this->getChildHtml('media_mobile') ?>
                        <div class="product-price">
                            <?php echo $this->__('Our Price') . ': ' . $this->getChildHtml('product_type_data') ?>
                        </div>
                        <div id="mw-fg-product-view">
                            <?php echo Mage::helper('freegift')->renderFreeGiftLabel($_product);?>
                            <?php echo Mage::helper('freegift')->renderFreeGiftCatalogList($_product);?>
                        </div>
                        <div class="product-sku">
                            <?php echo $this->__('Stock code') . ': ' . $_product->getSku();?>
                        </div>

                        <div class="estimatedeliver">
                            <?php echo $_product->getData('estimatedeliver');?>
                        </div>

                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        <?php endif;?>

                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                        <?php endif;?>

                        <?php if ($_product->isSaleable()):?>
                            <?php echo $this->getChildHtml('addtocart') ?>

                            <?php  if($_product->getData('tradein_enable')
                                        && Mage::getStoreConfig('magedevgroup_tradein/general/module_enable')) {
                                      echo $this->getChildHtml('tradein_button');
                                    }
                            ?>
                        <?php endif;?>

                        <?php echo $this->getChildHtml('fileupload') ?>

                        <?php echo $this->getChildHtml('product_info_custom_text') ?>
                        <?php
                        if (in_array($_product->getSku(), $showImage) ) {
                        echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_custom_image')->toHtml();
                        }
                        ?>
                        <div class="product-collateral toggle-content tabs">
                            <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                                <dl id="collateral-tabs" class="collateral-tabs clearfix">
                                    <?php foreach ($detailedInfoGroup as $alias => $html):?>
                                        <dt class="tab"><span><?php echo $this->getChildData($alias, 'title'); ?></span></dt>
                                        <dd class="tab-container">
                                            <div class="tab-content"><?php echo $html ?></div>
                                        </dd>
                                    <?php endforeach;?>
                                </dl>
                            <?php endif; ?>
                        </div>

                    </div>
                </form>
                <script type="text/javascript">
                //<![CDATA[
                    var productAddToCartForm = new VarienForm('product_addtocart_form');
                    productAddToCartForm.submit = function(button, url) {
                        <?php if(Mage::helper('itactica_intenso')->formFieldsType() == 'mdformfields'): ?>
                        Object.extend(Validation, {
                            isVisible : function(elm) {
                                while(elm.tagName != 'BODY') {
                                    // validate hidden select boxes when chosen.js is enabled
                                    if (elm.className.indexOf('super-attribute-select') > -1 || elm.className.indexOf('product-custom-option') > -1) {
                                        elm = elm.parentNode;
                                    }
                                    if(!$(elm).visible()) return false;
                                    elm = elm.parentNode;
                                }
                                return true;
                            }
                        });
                        <?php endif; ?>
                        if (this.validator.validate()) {
                            var form = this.form;
                            var oldUrl = form.action;

                            if (url) {
                               form.action = url;
                            }
                            var e = null;
                            try {
                                this.form.submit();
                            } catch (e) {
                            }
                            this.form.action = oldUrl;
                            if (e) {
                                throw e;
                            }

                            if (button && button != 'undefined') {
                                button.disabled = true;
                            }
                        }
                    }.bind(productAddToCartForm);

                    productAddToCartForm.submitLight = function(button, url){
                        if(this.validator) {
                            var nv = Validation.methods;
                            delete Validation.methods['required-entry'];
                            delete Validation.methods['validate-one-required'];
                            delete Validation.methods['validate-one-required-by-name'];
                            // Remove custom datetime validators
                            for (var methodName in Validation.methods) {
                                if (methodName.match(/^validate-datetime-.*/i)) {
                                    delete Validation.methods[methodName];
                                }
                            }

                            if (this.validator.validate()) {
                                if (url) {
                                    this.form.action = url;
                                }
                                this.form.submit();
                            }
                            Object.extend(Validation.methods, nv);
                        }
                    }.bind(productAddToCartForm);
                //]]>
                </script>
            </div>
        </div>
    </div>
    <div class="product-collateral-wrapper">
            <h3 style="border-bottom: 1px solid #ed121a;"></h3>
            <?php echo $this->getChildHtml('product.info.customblocks_orders') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>

        <?php if (!$_reviews): ?>
            <?php echo $this->getChildHtml('custom_info') ?>
        <?php endif; ?>

        <?php echo $this->getChildHtml('product_additional_data') ?>

<!--        <?php /*if (Mage::helper('core')->isModuleOutputEnabled('Yotpo_Yotpo')): */?>
        <div class="product-collateral yotpo-reviews clearfix row">
            <h3><?php /*echo $this->__('Reviews'); */?></h3>
            <div class="small-12 columns">
                <?php /*echo $this->getChildHtml('yotpo-reviews') */?>
            </div>
        </div>
        --><?php /*endif; */?>
        <div class="product-collateral finance clearfix row">
            <p data-magellan-destination="tab_finance"><a id="tab_finance"></a></p>
            <h3><?php echo $this->__('Finance'); ?></h3>
            <div class="small-12 columns">
                <?php echo $this->getLayout()->createBlock("pay4leter/info_financeinfo")
                    ->setProduct($_product)
                    ->toHtml(); ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('related_products') ?>
    </div>
</section>