<?php
/**
 * Renegade Group
 * 
 * Copyright (C) 2013 - 2014 QubeSys Technologies Pvt.Ltd. All rights reserved.
 * 

 * http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL.
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Products') ?></h4>
        <div class="right"><?php echo $this->getProductAddButtonHtml(); ?></div>
    </div>
    <div id="product_box" class="box">
        <div id="productGrid"><!--Load grid Here--></div>
        <?php $i = 0;
        if (isset($_familyProducts) && count($_familyProducts)>0 && $_familyProducts!=false): ?>
            <div class="grid tier form-list" id="box">
                <table class="border" cellpadding="0" cellspacing="0" id="input-container">
                    <thead>
                        <tr class="headings">
                            <th><?php echo $this->__('ID') ?></th>
                            <th><?php echo $this->__('Name') ?></th>
                            <th><?php echo $this->__('SKU') ?></th>
                            <th><?php echo $this->__('Type') ?></th>
                            <th><?php echo $this->__('Product ID') ?></th>
                            <th class="last"><?php echo $this->__('Delete') ?></th>
                        </tr>
                    </thead>
                    <tbody>
<?php foreach ((array)$_familyProducts as $_familyProduct): ?>
                    <tr id="product_entity_id_<?php echo $_familyProduct->getEntityId(); ?>" class="selection">
                        <td>
                            <input type="hidden" value="<?php echo $_familyProduct->getEntityId(); ?>"                      name="family_product[<?php echo $i; ?>][product_id]"  id="family_product[<?php echo $i; ?>][product_id]">
                            <input type="hidden" value="<?php echo $_familyProduct->getSku(); ?>"                           name="family_product[<?php echo $i; ?>][product_sku]" id="family_product[<?php echo $i; ?>][product_sku]">
                            <input type="hidden" value="<?php echo $_familyProduct->getMyProductFamilyContentId(); ?>"      name="family_product[<?php echo $i; ?>][product_family_content_id]" id="family_product[<?php echo $i; ?>][product_family_content_id]">

                            <?php echo $_familyProduct->getMyProductFamilyContentId(); ?>
                        </td>
                        <td>
                            <div class="nobr"><?php echo $_familyProduct->getName(); ?></div>
                        </td>
                        <td>
                            <div class="nobr"><?php echo $_familyProduct->getSku(); ?></div>
                        </td>
                        <td>
                            <?php echo $_familyProduct->getTypeId(); ?>
                        </td>
                        <td>
                            <?php echo $_familyProduct->getEntityId(); ?>
                        </td>

                        <td class="last">
                            <span title="Delete Row">
                                <button style="" class="scalable delete icon-btn" onclick="manageProduct.remove(this)" type="button">
                                    <span>Delete</span>
                                </button>
                            </span>
                        </td>
                    </tr>
                    <?php $i++; ?>
<?php endforeach; ?>
                </tbody>
            </table>

        </div>
<?php endif; ?>
                </div>
            </div>



            <script type="text/javascript">
                // re-bind form elements onchange
                //<![CDATA[
                varienWindowOnload(true);
                var productTemplateBox = '<table class="border" cellpadding="0" cellspacing="0">' +
                    '    <thead>' +
                    '        <tr class="headings">' +
                    '           <th><?php echo $this->__('ID') ?></th>' +
                    '           <th><?php echo $this->__('Name') ?></th>' +
                    '           <th><?php echo $this->__('SKU') ?></th>' +
                    '           <th><?php echo $this->__('Type') ?></th>' +
                    '           <th><?php echo $this->__('Product ID') ?></th>' +
                    '        <th class="last"><?php echo $this->__('Delete') ?></th>' +
                    '        </tr>' +
                    '    </thead> ' +
                    '    <tbody>' +
                    '    </tbody>' +
                    '</table>';
                    var productTemplateRow = '<td>' +
                        '    <input type="hidden" value="{{product_id}}" name="family_product[{{index}}][product_id]" id="family_product[{{index}}][product_id]">' +
                        '    <input type="hidden" value="{{product_sku}}" name="family_product[{{index}}][product_sku]" id="family_product[{{index}}][product_sku]">' +
                        '     &nbsp;' +
                        '</td>' +
                        '<td>' +
                        '    <div class="nobr">{{product_name}}</div>' +
                        '</td>' +
                        '<td>' +
                        '    <div class="nobr">{{product_sku}}</div>' +
                        '</td>' +
                        '<td>' +
                        '    {{product_type}}' +
                        '</td>' +
                        '<td>' +
                        '     {{product_id}}' +
                        '</td>' +
                        '<td class="last">' +
                        '    <span title="Delete Row">' +
                        '       <?php echo $this->getProductDeleteButtonHtml() ?>' +
                        '    </span>' +
                        '</td>' ;

                Product = Class.create();
                Product.prototype = {

                    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
                    templateBox : '',
                    templateRow : '',
                    itemsCount : <? echo $i; ?>,
                    row : null,

                    gridSelection : new Hash(),

                    initialize : function() {
                        this.templateBox = '<div class="grid tier form-list" id="box">' + productTemplateBox + '</div>';
                        this.templateRow = '<tr id="product_entity_id_{{product_id}}" class="selection">' + productTemplateRow + '</tr>';
                    },

                    showGridBox : function(event) {
                        this.gridSelection.unset(0);
                        new Ajax.Updater(
                                'productGrid',
                                '<?php echo $this->getProductGridContainerUrl() ?>',
                                {
                                    method: 'post',
                                    evalScripts : true,
                                    onSuccess: function() {
                                        $('loading-mask').hide();

                                        if (Event.element(event).tagName.toLowerCase() != 'button') {var button = Event.element(event).up('button');} else {var button = Event.element(event);}
                                        button.hide();
                                    }
                                }
                        );
                    },

                    addRow : function (data) {
                        var box = null;
                        if (!(box = $('box'))) {
                            this.addBox('product_box');
                            box = $('box');
                        } else {
                            box.show();
                        }
                        if(!data){
                            var data = {};
                        }
                        data.index = this.itemsCount++;
                        this.template = new Template(this.templateRow, this.templateSyntax);
                        var tbody = $$('#box tbody');
                        Element.insert(tbody[0], {'bottom':this.template.evaluate(data)});
                    },
                    productGridCheckboxCheck : function(element) {
                        var tr = element.up('tr');

                        if (element.value > 0) {
                            if (element.checked) {
                                if (!this.gridSelection.get(0)) {
                                    this.gridSelection.set(0, new Hash());
                                }
                                this.gridSelection.get(0).set(element.value, $H({}));
                                this.gridSelection.get(0).get(element.value).set('product_name', tr.select('td.product_name')[0].innerHTML);
                                this.gridSelection.get(0).get(element.value).set('product_id', element.value);
                                this.gridSelection.get(0).get(element.value).set('product_sku', tr.select('td.product_sku')[0].innerHTML);
                                this.gridSelection.get(0).get(element.value).set('product_type', tr.select('td.product_type')[0].innerHTML);
                            }else{
                                if(this.gridSelection.get(0).get(element.value)){
                                    this.gridSelection.get(0).unset(element.value);
                                }
                            }

                        }
                    },
                    productGridAddSelected : function(event) {
                        $('productGrid').innerHTML = '';
                        $('add_product_button').show();
                        if(this.gridSelection.get(0))
                        {
                            this.gridSelection.get(0).each(
                                function(pair) {
                                    var data = {
                                        'product_name' : pair.value.get('product_name').trim(),
                                        'product_id' : pair.value.get('product_id').trim(),
                                        'product_sku' : pair.value.get('product_sku').trim(),
                                        'product_type' : pair.value.get('product_type').trim()
                                    };
                                    if($('product_entity_id_'+data.product_id) == undefined)
                                    {
                                        manageProduct.addRow(data);
                                    }
                                }
                            );
                        }
                    },

                    remove : function(element) {
                        tr = element.up('tr');
                        tr.remove();
                    },

                    addBox : function (parentIndex) {
                    var div = $(parentIndex)
                    this.template = new Template(this.templateBox, this.templateSyntax);
                    var data = {};
                    Element.insert(div, {'bottom':this.template.evaluate(data)});
                    }
                }
        manageProduct = new Product();
    //]]>
</script>