<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
//$data= $this->getQuoteData() ;
$_payHelper = Mage::helper('pay4leter');

?><?php if ($_SESSION['PAY4LATER_SESSION'] == 0): ?>
    <?php $_code = $this->getMethodCode() ?>
    <div id="payment_form_pay4leter" style="display:none;">
        <input type="hidden" name="apiKey" value="<?php echo $_payHelper->apiKey; ?>">
        <ul class="form-list paymentsage">
            <li id="serversecure">
                <span>
                <?php
                echo $this->__('You will be redirected to pay4later website when you place an order.') ?>
                    </span>
            </li>

        </ul>
    </div>

<?php endif; ?>
<script language="javascript">
    jQuery(document).ready(function ($) {
        var session = <?php echo $_SESSION['PAY4LATER_SESSION'];?>;
        console.log(session);
        if (session == 1) {
            $("#dt_method_pay4leter").hide();
        }
    });
</script>