<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$width = 500;
if (Mage::registry('media_mobile_image_size')) {
    list($maxHeight, $resizeAsSquare, $baseImageSize) = Mage::registry('media_mobile_image_size');
} else {
    $maxHeight = 500;
    $baseImageSize = 1200;
}
?>
<div class="mobile-gallery">
    <div class="product-label-placeholder" data-productid="<?php echo $_product->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel" data-source="product"></div>
    <ul class="orbit-container" id="gallery-image-mobile" data-orbit data-options="animation:slide;animation_speed:600;timer:false;slide_number:false;variable_height:true;swipe:true;navigation_arrows:false;outside_bullets:true;">
        <?php $mainImageSrc = $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$maxHeight); ?>
        <li class="item">
            <a class="lightbox-mobile product-image" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($baseImageSize); ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$maxHeight); ?>" alt="TEST" width="<?php echo $width; ?>" height="<?php echo $maxHeight; ?>">
            </a>
        </li>
        <?php if (count($this->getGalleryImages()) > 0): ?>
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php if ($this->isGalleryImageVisible($_image) && strpos($mainImageSrc, $_image->getFile()) === false): ?>
                    <li class="item">
                        <a class="lightbox-mobile product-image" href="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize($baseImageSize); ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $_image->getFile())->resize($width,$maxHeight); ?>" alt="" width="<?php echo $width; ?>" height="<?php echo $maxHeight; ?>">
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</div>
