<?php
if(Mage::helper('mw_socialgift')->isEnabled() && Mage::helper('mw_socialgift')->isAddToCartOn() ) :
    $helper = Mage::helper('mw_socialgift');
    $SocialGiftStatus = Mage::getSingleton('checkout/session')->getSocialGiftStatus();
?>

    <?php if( ($this->getCollection()->getSize() > 0) && (count($this->getFreegiftIds()) > 0) ): ?>
        <?php // Show Social Gift Reminder
            $arrShowin = array();
            $current_controller =  $this->getRequest()->getControllerName();
            if ($current_controller == 'cart') {
                $arrShowin = array(1,3);
            } else {
                $arrShowin = array(2,3);
            }
            $showin = $helper->showIn();

        ?>
        <div class="socialgift_rules_container">
        <?php if(in_array($showin,$arrShowin)) { ?>
                    <?php if ($SocialGiftStatus == 'shared') { ?>
                        <div class="socialgift_rules">
                            <div class="jcarousel-wrapper">
                                <h2><span class="sg_add_gift_success"> </span> <?php echo Mage::helper('mw_socialgift')->__('Thank you! You have shared product to social network, You still have %s gift(s) to choose, <a href="javascript:void(0);" class="fancybox" title="Add gift to cart"> <i> click here </i></a>', Mage::getSingleton('checkout/session')->getNumberSocialGiftRule() - Mage::getSingleton('checkout/session')->getNumberSocialGift()) ?></h2>
                            </div>
                        </div>
                    <?php } ?>
        <?php   } ?>
        </div>
    <?php endif;?>
<?php endif;?>