<?php
    $width = Mage::getStoreConfig('noisypopup/general/width');
    $height = Mage::getStoreConfig('noisypopup/general/height');
    $delay = Mage::getStoreConfig('noisypopup/general/delay');
    $cookieExp = Mage::getStoreConfig('noisypopup/general/cookieexp');
    $showOncePerSession = Mage::getStoreConfig('noisypopup/general/showoncepersession');
?>

<div id="bio_ep">
    <div class="popup-header">
        Leaving Already?
    </div>
    <div class="popup-content">
        If there is anything we can<br>
        help with then call us now on
        <div class="popup-call">
            <a href="tel:03435236169">03435236169</a>
        </div>
        <div class="popup-footer">We'll be happy to answer any of your questions</div>
    </div>
</div>

<script type="text/javascript">
    window.onload = function () {
        bioEp.init({
            width: <?php echo $width; ?>,
            height: <?php echo $height; ?>,
            delay: <?php echo $delay; ?>,
            cookieExp: <?php echo $cookieExp; ?>,
            showOncePerSession: <?php echo $showOncePerSession; ?>,
            css: '#bio_ep_close{position: absolute;left: 100%;margin: -5px 0 0 -12px;width: 20px;height: 20px;color: #fff;font-size: 12px;font-weight: bold;text-align: center;border-radius: 50%;background-color: #5c5c5c;cursor: pointer;line-height: 20px;}'
        });
    }
</script>
