<?php
$_helper    = $this->helper('catalog/output');
$_category  = Mage::getModel('catalog/layer')->getCurrentCategory();
$_categoryBlock = Mage::getSingleton('Mage_Catalog_Block_Category_View');
$_isRssCatalogEnable = Mage::getStoreConfig('rss/catalog/category');
$_isSearchResults = false;
$_isCMSPage = Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms';
// if current page is search result show search term as title instead of category name
$pathInfo = Mage::helper('core/url')->getCurrentUrl();
$pageTitle = $_helper->categoryAttribute($_category, $_category->getName(), 'name');
if (stripos($pathInfo, '/catalogsearch/result') !== false) {
    $pageTitle = Mage::helper('catalogsearch')->getQueryText();
    $_isSearchResults = true;
}
if (stripos($pathInfo, '/catalogsearch/advanced/result') !== false) {
    $pageTitle = $this->__('Search results');
    $_isSearchResults = true;
}
// if current page is a CMS page remove the title
if ($_isCMSPage) {
    $pageTitle = '&nbsp;';
}
?>

<?php if($this->getCollection()->getSize()): ?>
    <div class="row toolbar">
        <div class="small-12 medium-12 large-12 columns">
            <?php if (!$_isCMSPage): ?>
                <p id="amount" class="amount">
                    <?php if($this->getLastPageNum()>1): ?>
                        <?php echo $this->__('Items %s - %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                    <?php else: ?>
                        <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                    <?php endif; ?>
                </p>
            <?php endif; ?>
        </div>
        <div class="actions small-12 medium-12 large-12 columns">
            <?php if( $this->isEnabledViewSwitcher() ): ?>
                <?php $_modes = $this->getModes(); ?>
                <?php if($_modes && count($_modes)>1): ?>
                    <ul class="button-group">
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <li><a href="#" class="button icon-<?php echo strtolower($_code); ?> toggle-<?php echo strtolower($_code); ?> <?php if($this->isModeActive($_code)): ?>active<?php endif; ?>" title="<?php echo $_label ?>"><span class="a11y"><?php echo $_label ?></span></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif ?>
