<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php 
$_menu = $this->getHtml('level-top');
$_linksArray = @unserialize(Mage::getStoreConfig('intenso/header/main_menu_links', Mage::app()->getStore()));
$_offcanvasLinksArray = @unserialize(Mage::getStoreConfig('intenso/header/mobile_offcanvas_links', Mage::app()->getStore()));
?>

<nav class="top-bar right-off-canvas-menu expanded main-nav <?php echo Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()); ?>" data-topbar>
    <ul class="title-area">
        <li class="name show-for-small-only">
            <?php echo $this->getChildHtml('offcanvasSearch') ?>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><?php echo $this->__('Menu'); ?></a></li>
    </ul>
    <section class="top-bar-section clearfix <?php echo Mage::getStoreConfig('intenso/header/main_menu_event', Mage::app()->getStore()); ?>">
        <!-- Right Nav Section -->
        <ul class="right show-for-large-up">
            <li class="has-dropdown hide-for-small-only">
            	<a href="<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { echo $this->getUrl('customer/account'); } else { echo Mage::helper('customer')->getLoginUrl(); } ?>"><span class="sup truncate"><?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?><?php echo $this->__('Hello, %s', Mage::getSingleton('customer/session')->getCustomer()->getFirstname()); ?><?php else: ?><?php echo $this->__('Hello. Sign in'); ?><?php endif; ?></span><?php echo $this->__('Your Account'); ?></a>
                <ul class="dropdown account-dropdown">
                    <li class="arrow-box">
                      	<div class="bg-box">
                      		<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                      		<a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="button sign-in"><?php echo $this->__('Log Out'); ?></a>
                          	<?php else: ?>
                          	<a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" class="button sign-in"><?php echo $this->__('Sign in'); ?></a>
                          	<p class="small"><?php echo $this->__('New customer?'); ?> <a href="<?php echo $this->getUrl('customer/account/create'); ?>" ><?php echo $this->__('Start here'); ?></a>.</p>
                          	<?php endif; ?>
                        </div>
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown hide-for-small-only"> 
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span aria-hidden="true" class="icon-cart"></span><span class="sup"><?php echo trim($this->getChildHtml('cart_summary')); ?> <?php echo $this->__('items'); ?></span><?php echo $this->__('Cart'); ?></a>
                <ul class="dropdown cart-dropdown">
                    <li class="arrow-box">
                        <?php echo $this->getChildHtml('minicart_head'); ?>
                    </li>
                </ul>
            </li>
        </ul>
		<!-- Left Nav Section -->
		<ul class="left">
			<?php if (Mage::getStoreConfig('intenso/header/show_home_link', Mage::app()->getStore()) ||
                Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
				<li class="last<?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?> show-for-small-only<?php endif; ?>">
					<a href="<?php echo $this->getUrl('') ?>"><span class="show-for-small-only icon-home"></span><?php echo $this->__('Home'); ?></a>
				</li>
			<?php endif; ?>
      <?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
        <li class="last has-dropdown hide-for-small-only vertical-menu-link">
          <a href="<?php echo $this->getUrl('') ?>">
            <span class="show-for-large-only sup"><?php echo $this->__('Shop by'); ?></span>
            <span class="vmenu-title"><?php echo $this->__('Category'); ?></span>
          </a>
        </li>
      <?php endif; ?>
			<?php if (Mage::getStoreConfig('intenso/header/show_categories', Mage::app()->getStore())): ?>
				<li class="show-for-small-only group-title"><?php echo $this->__('Shop'); ?></li>
				<?php if ($_menu): ?>
					<?php echo $_menu ?>
				<?php endif ?>
			<?php endif ?>
			<?php if ($_linksArray): ?>
				<?php foreach ($_linksArray as $menuItem): ?>
					<li class="custom-menu<?php if ($menuItem['static_block']): ?> has-dropdown-for-large<?php endif; ?>">
						<a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a>
						<?php if ($menuItem['static_block']): ?>
							<div class="dropdown arrow-box">
								<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($menuItem['static_block'])->toHtml(); ?>
							</div>
						<?php endif; ?>
					</li>
				<?php endforeach; ?>
			<?php endif; ?>
			<li class="show-for-small-only group-title"><?php echo $this->__('Pages'); ?></li>
			<li class="show-for-small-only"><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Cart'); ?></a></li>
			<li class="show-for-small-only"><a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo $this->__('Your Account'); ?></a></li>
			<?php if ($this->helper('wishlist')->isAllow()): ?>
				<li class="show-for-small-only"><a href="<?php echo $this->getUrl('wishlist'); ?>"><?php echo $this->__('Your Wish List'); ?></a></li>
			<?php endif; ?>
			<?php if ($_offcanvasLinksArray): ?>
				<?php foreach ($_offcanvasLinksArray as $menuItem): ?>
					<li class="show-for-small-only"><a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a></li>
				<?php endforeach; ?>
			<?php endif; ?>
		</ul>
        <ul class="bottom">
            <li class="custom-menu first">
            </li>
            <li class="custom-menu second">
            </li>
            <div class="border"></div>
            <li class="custom-menu third">
            </li>
            <div class="border"></div>
            <li class="custom-menu fourth">
                <a href="#pop_up_90_returns" class="open-popup-link" data-effect="mfp-zoom-in"><span>Show inline popup</span></a>
            </li>
            <div class="border"></div>
            <li class="custom-menu" style="padding-top: 18px; height: 50px; width: 25%;">
                <div class="trustpilot-widget" data-locale="en-GB" data-template-id="5419b732fbfb950b10de65e5" data-businessunit-id="4cf3949700006400050e31b7" data-style-height="50px" data-style-width="100%" data-theme="light">
                    <a href="https://uk.trustpilot.com/review/www.kronosav.com" target="_blank">Trustpilot</a>
                </div>
            </li>
        </ul>
	</section>
    <!-- Popup pop_up_90_returns -->
    <div id="pop_up_90_returns" class="white-popup mfp-hide">
        <div class="popup-container">
            <p class="heading-popup">Up to 90 Day Returns!</p>
            <p class="text-popup">
                Returns with Kronos AV are easy and flexible. We will accept returned goods up to 90 days from purchase
                with the following conditions & restrictions as summarised below.
                For more details please read our Terms & Conditions of Sale, a link is shown in the footer of our home page.
            </p>
            <p class="heading-popup">Reevaluating your purchase?</p>
            <p class="text-popup">
                It is no problem if you change your mind however please be aware that all goods must be returned in as new,
                unused and re-saleable condition. This means that all packaging must be intact,
                all accessories are complete & present in their original wrappers and any free items are also
                returned with the goods. All packaging must be free from any form of damage, including tears, rips or dents.
                All inner packaging also needs to be in perfect, as new condition. Substantially the product must be returned
                in the same condition as you would expect to receive a new unit in. The cost of returning the goods will be
                the customer's responsibility. We recommend sending parcels as a minimum signed for and insured.
                All faulty items must be returned complete (including packaging)  and will be repaired under the manufacturer's warranty.
            </p>
            <p class="heading-popup">How returns work...</p>
            <p class="text-popup">
                Returns are dependent on how long you have had the goods,
                and their condition. The time period will depend on what we can offer with regards to returns.
                If your goods are faulty, we shall of course accept the return and offer a repair or brand new item
                depending on the fault, within 28 days from delivery. Any product which is still
                in warranty after 30 days will be repaired, as per the manufactures warranty regulations.
                If you have simply changed your mind, please follow the subsequent guide.
                Please again note all products must be in as new, undamaged & resellable condition,
                with all accessories and free products present.
            </p>
            <div class="table-popup">
                <span class="img-table"></span>
            </div>
            <p class="heading-popup">Exchange</p>
            <p class="text-popup">
                This is were you return your item and we will exchange it for another item of equal or higher value.
                If the item you wish to change to is of higher value you only pay the difference.
                If the item is of a lower value we will issue you with a credit note for the difference which you
                can spend with us at a later date.
            </p>
            <p class="text-popup">
                An exchange will require the customer to return their purchased item and we will exchange it for
                a good of similar value. We can also offer exchanges for goods of a higher or lower value.
                In the case of a lower valued product, the customer will be issued with a credit note for the difference
                in cost which can be used to purchase with us in the future.
                If you wish to exchange it for an item of higher value, the customer will simply pay the difference in cost.
            </p>
            <p class="heading-popup">Credit Note</p>
            <p class="text-popup">
                This is where you return your item and we issue you with a credit note which you can use against
                another purchase with us.
            </p>
            <p class="text-popup">
                Credit notes may be issued and these can be used against further purchases with us.
            </p>
            <p class="heading-popup">Refund</p>
            <p class="text-popup">
                This is where you return your item and we issue a refund back to the same method you paid with. e.g.
                the same credit card. This is not available after 14 days, only exchange or credit note is available after 14 days.
            </p>
            <p class="text-popup">
                Items can be returned for a full refund, if they correspond
                to the above regulations & our Term and Conditions.
                Refunds must be returned back to the same method of payment used when the purchase was made.
                e.g. the refund must be processed with the same credit card the purchase was made from.
            </p>
            <p class="heading-popup">25% Restocking Fee</p>
            <p class="text-popup">
                When items are returned within 29-90 days of delivery a restocking fee of 25% will be charged.
                This charge will be deducted from the price of which was paid initially for the item.
                This cost will be deducted from the credit note or exchange which will be issued
                to you upon our receipt of delivery for the returned goods.
                Goods must be returned for inspection before any refund,
                credit note or exchange can be issued. Unfortunately product prices will
                decrease over time, so this is the reason for the re stocking fee,
                as the goods will no longer we worth the same value as when they were first purchased.
            </p>
            <p class="heading-popup">Exceptions for returns</p>
            <p class="text-popup">
                Returns cannot be accepted if any of the following conditions are connected with your purchase.
                If the item is built to order, or is ordered in specially then returns cannot be accepted unless
                there is a fault with the goods, which can be verified by the manufacturer.
                In this case, the goods will be repaired or exchanged for a brand new item and returned to the customer.
                <span class="padding"></span>
                Any items which are purchased on sale or at a reduced cost are also exempt from being returned.
                Goods which are on sale may be returned if a genuine fault, which is verified by
                the manufacturer is found and will repaired under manufacturers warranty.
                <span class="padding"></span>
                Headphones or earphones are also exempt form return to health & safety reasons.
                <span class="padding"></span>
                Again if the goods are not returned in perfect, as new, unused and resellable condition,
                with all accessories, packaging and free items present then a refund/exchange/credit
                note may not be able to be issued. This includes all inner and outer packaging,
                which must be free from any form of damage including rips, tears marks or dents.
                Refusal to offer an exchange/refund or credit note will be at the discretion of Kronos AV,
                if a valid reason for refusal is found.
                <span class="padding"></span>
                Products purchased with Deco/Pay4Later on 0% finance cannot be exchanged
                as this is a legally binding agreement, and is only valid against the
                products which were stated on the original agreement.
                It is with the discretion of the finance provider whether the finance agreement
                can be amended in the case of an exchange.
                <span class="padding"></span>
                Goods which were purchased past 90 days cannot be returned, unless a warranty repair is necessary.
                <span class="padding"></span>
                Please refer to our Terms and Conditions for full details on the above conditions.
            </p>
        </div>
    </div>
</nav>

