<?php if ($this->shouldDisplay()): ?>
    <?php $_xeroStatus = $this->getXeroOrderStatus() ?>
    <div class="connectaccounts_container">
        <div class="box-left" id="connectaccounts_block">

            <div class="entry-edit">

                <div class="entry-edit-head">

                    <h4 class="icon-head head-account"><?php echo Mage::helper('foomanconnect')->__(
                            'Fooman Connect'
                        ) ?> </h4>

                </div>
                <div class="fieldset">
                    <table cellspacing="0" class="form-list">

                        <?php if ($this->isExported()): ?>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('foomanconnect')->__(
                                            'Exported to Xero'
                                        ) ?></label></td>
                                <td><strong><?php echo Mage::helper('catalog')->__('Yes') ?> <img
                                            src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16"
                                            height="16" alt=""/></strong></td>
                            </tr>
                            <?php if ($_xeroStatus && $_xeroStatus->getXeroInvoiceNumber()): ?>
                                <tr>
                                    <td class="label"><label><?php echo Mage::helper('foomanconnect')->__(
                                                'Xero Invoice Number'
                                            ) ?></label></td>
                                    <td><strong><?php echo $_xeroStatus->getXeroInvoiceNumber() ?></strong></td>
                                </tr>
                                <?php if ($this->displayPayments()): ?>
                                    <tr>
                                        <td class="label"><label><?php echo Mage::helper('foomanconnect')->__(
                                                    'Payments'
                                                ) ?></label></td>
                                        <td>
                                            <?php $_payments = $this->getXeroPayments() ?>
                                            <?php if (!empty($_payments['payments'])): ?>
                                                <?php foreach ($_payments['payments'] as $_payment): ?>
                                                    <p><span
                                                            style="display:block;float:left;width:70px;"><strong><?php echo Mage::app(
                                                                )->getStore()->formatPrice(
                                                                    $_payment['amount']
                                                                ) ?></strong></span> <span
                                                            style=""><?php echo Mage::helper('core')->formatDate(
                                                                $_payment['date'], 'medium'
                                                            ) ?></span></p>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <?php echo Mage::helper('foomanconnect')->__(
                                                    'No Payments have been recorded in Xero.'
                                                ) ?> <br/>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    <?php if (!empty($_payments['amountDue'])): ?>
                                        <tr>
                                            <td class="label"><label><?php echo Mage::helper('foomanconnect')->__(
                                                        'Amount Due'
                                                    ) ?></label></td>
                                            <td><strong><?php echo Mage::app()->getStore()->formatPrice(
                                                        $_payments['amountDue']
                                                    ) ?></strong></td>
                                        </tr>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <tr>
                                    <td colspan="2"><a target="_blank"
                                                       href="<?php echo $this->getXeroUrl() ?>"><?php echo Mage::helper(
                                                'foomanconnect'
                                            )->__('View in Xero') ?></a></td>
                                </tr>
                            <?php endif; ?>
                        <?php else: ?>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('foomanconnect')->__(
                                            'Exported to Xero'
                                        ) ?></label></td>
                                <td><strong style="line-height:16px;"><?php echo Mage::helper('catalog')->__('No') ?>
                                        <img style="vertical-align:middle;"
                                             src="<?php echo $this->getSkinUrl('images/error_msg_icon.gif') ?>"
                                             width="16" height="16" alt=""/></strong></td>
                                <td width="30%"><?php echo $this->getChildHtml('export_now_button') ?></td>
                            </tr>
                            <?php if ($this->getXeroLastValidationErrors()): ?>
                                <tr>
                                    <td class="label"><label><?php echo Mage::helper('foomanconnect')->__(
                                                'Last Error Message'
                                            ) ?></label></td>
                                    <td class="value" colspan="2">
                                        <?php foreach ($this->getXeroLastValidationErrors() as $_validationError) : ?>
                                            <?php echo $_validationError ?><br/>
                                        <?php endforeach; ?>
                                    </td>
                                </tr>
                            <?php endif; ?>
                        <?php endif; ?>
                    </table>
                </div>
            </div>
        </div>

        <div class="clear"></div>
    </div>
<?php endif; ?>
