<?php

/** @var Magedevgroup_ProductVideo_Block_Product_View_Video $block */
$block = $this;

$embedUrl = $block->getVideo();
if ($embedUrl != null):
    ?>
    <p data-magellan-destination="youtube_video"><a id="youtube_video"></a></p>
    <div class="videoWrapper">
        <iframe width="850" height="478" src="//<?php echo $embedUrl; ?>" frameborder="0" allowfullscreen></iframe>
    </div>
    <p data-magellan-destination="youtube_video"><a id="youtube_video"></a></p>
    <style>
        .videoWrapper {
            position: relative;
            padding-bottom: 56.25%; /* 16:9 */
            padding-top: 25px;
            height: 0;
        }
        .videoWrapper iframe {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }
    </style>
    <script>
        // Find all YouTube videos
        var $allVideos = $("iframe[src^='//www.youtube.com']"),

            // The element that is fluid width
            $fluidEl = $("body");

        // Figure out and save aspect ratio for each video
        $allVideos.each(function() {

            $(this)
                .data('aspectRatio', this.height / this.width)

                // and remove the hard coded width/height
                .removeAttr('height')
                .removeAttr('width');

        });

        // When the window is resized
        $(window).resize(function() {

            var newWidth = $fluidEl.width();

            // Resize all videos according to their own aspect ratio
            $allVideos.each(function() {

                var $el = $(this);
                $el
                    .width(newWidth)
                    .height(newWidth * $el.data('aspectRatio'));

            });

// Kick off one resize to fix all videos on page load
        }).resize();
        
    </script>
    <?php
endif;