<?php $typeArray=$this->typeArray;

$product=Mage::registry('current_product');
$product_id = $product->getId();

$productPrice = $product->getPrice();

$pay4laterArray = Mage::getStoreConfig('payment/pay4later');
$minimumLoanValue = $pay4laterArray['loanvalue'];
$infopaylater = $pay4laterArray['infopaylater'];

$discountJsonArray = array();
$i = 1;
$first_key = 'ONIF6';
$firstPertange = '10';
$firstPertangeArray = array();
foreach($typeArray as $ty_key => $ty_value){
    if($i == 1){
        reset($typeArray);
        $first_key = key($typeArray);
        $firstType = $first_key;
        reset($typeArray[$first_key]['pertange']);
        $firstPertangekey = key($typeArray[$first_key]['pertange']);
        $firstPertangeArray = $typeArray[$first_key]['pertange'];
        $firstPertange =  $typeArray[$first_key]['pertange'][$firstPertangekey];
        
    }
    foreach(range('a','f') as $key){
        $discountJsonArray[$ty_key][] =  $ty_value['pertange'];
    }

$i++;
}

$discountJson = json_encode($this->discountArray);
if($pay4laterArray['product_detail_active'] == 1):?>
?>
<div class="desktop_pay4later_view"	>
<form method="POST"  >
    <table class="bg-box pay4later_details" style="clear:both"  >
        <tbody >
            <tr>
                <td>Product Type</td>
                <td class="var_product_type">
                    <select name="var_product_type" class="pay_class select-box-width" id="var_product_type">
                        <?php foreach($typeArray as $t_key => $t_value):?>
                            <option value="<?php echo $t_key;?>"><?php echo $t_value['name']; ?></option>
                        <?php endforeach;?>
                    </select>
                </td>
            </tr>
            <tr style="display: none">
                <td>Cost of Goods (&pound;)</td>
                <td class="var_cost_of_goods"><input type="hidden" readonly="readonly" id="var_cost_of_goods" name="var_cost_of_goods" size="5" value="<?php echo $productPrice;?>" /></td>
            </tr>
            <tr>
                <td>Deposit Percentage</td>
                <td class="var_deposit_percentage">
                    <select name="var_deposit_percentage" class="pay_class select-box-width"  id="var_deposit_percentage">
                    <?php foreach($firstPertangeArray as $key1 => $value1):?>
                            <option value="<?php echo $value1;?>"><?php echo $value1;?>%</option>
                    <?php endforeach;?>
                         </select>
                </td>
            </tr>
            <tr style="display: none">
                <td>Deposit Amount (&pound;)</td>
                <td class="var_deposit_amount"><input type="hidden" id="var_deposit_amount" name="var_deposit_amount" size="4" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr style="display: none">
                <td colspan="3"><input type="button" id="params"  value="Update Values" /></td>
            </tr>
        </tfoot>
    </table>
</form>

<table class="bg-box pay4later_details" style="margin-bottom:10px;">
    <!--<thead>
        <tr>
            <th><strong>Property Name</strong></th>
            <th><strong>Property Value</strong></th>
            
        </tr>
    </thead>-->
    <tbody>
       
        <tr>
            <td>Deposit you Pay</td>
            <td id="deposit_amount" class="weight-700" ></td>
        </tr>
        <!--
        <tr>
            <td>Percentage of Deposit</td>
            <td id="deposit_percentage" class="weight-700"></td>
        </tr>-->
        
           <tr>
            <td>Monthly Instalment</td>
            <td id="cost_per_month" class="weight-700"></td>
        </tr>
		
		
		<tr>
            <td>Rate of Interest (fixed)</td>
            <td id="rate_of_interest_frm" class="weight-700"></td>
        </tr>
		
		
         <tr>
            <td>Cash Price</td>
            <td id="cost_of_goods" class="weight-700"></td>
        </tr>
         <tr>
            <td>Amount of Loan</td>
            <td id="credit_amount" class="weight-700"></td>
        </tr>
         <tr>
            <td>Cost of Loan</td>
            <td id="loan_cost" class="weight-700"></td>
        </tr>
          <tr>
            <td>Total Amount Payable</td>
            <td id="total" class="weight-700"></td>
        </tr>
        <tr>
            <td>Duration of Agreement</td>
            <td id="finance_term" class="weight-700"></td>
        </tr>
        
		<?php if($minimumLoanValue != ''):?>
		<tr>
            <td>Minimum loan value</td>
            <td id="min_loan_value" class="weight-700"><?php echo "&#163;".$minimumLoanValue;?></td>
        </tr>
		<?php endif;?>
        
		
		<?php if($infopaylater != ''):?>
        <tr>
		<td colspan="2" class="pay4later_info">
			<?php echo $infopaylater;?>
		</td>
		</tr>
		<?php endif;?>
        
       
    </tbody>
</table>


</div>
<?php endif;?>
<script type="text/javascript">
    jQuery(document).ready(function() {
    
    
        loadFinanceDetails('<?php echo $first_key;?>', <?php echo $productPrice;?>, <?php echo $firstPertange;?>, 0);

        jQuery("#var_product_type").change(function(){
            var product_type = jQuery(this).val();
            
            var discountJson = jQuery.parseJSON('<?php echo $discountJson;?>');
            
           // console.log(product_type);
           // console.log(discountJson);        
            var discountLoop = discountJson[product_type];
            
            var option_content = '';
            jQuery( discountLoop ).each(function( index,value ) {
                option_content += '<option value='+value+'>'+value+'%</option>';
              });
              jQuery("#var_deposit_percentage").html(option_content);

            
        });
        jQuery(".pay_class").change(function(){
            var deposit_percentage = jQuery("#var_deposit_percentage").val();
            var var_cost_of_goods = jQuery("#var_cost_of_goods").val();
            var discounted_price = (var_cost_of_goods * deposit_percentage) / 100;
            discounted_price = discounted_price.toFixed(2);
            jQuery("#var_deposit_amount").val(discounted_price);


            var p1 = jQuery(":input[name='var_product_type']").val();
            var p2 = parseFloat(jQuery(":input[name='var_cost_of_goods']").val());
            var p3 = parseFloat(jQuery(":input[name='var_deposit_percentage']").val());
            var p4 = parseFloat(jQuery(":input[name='var_deposit_amount']").val());

            if (p1 == '' || isNaN(p2) || isNaN(p3) || isNaN(p4)) {
                alert("Please enter all the required fields in order to instantiate a new FinanceDetails object.");
            } else {
                loadFinanceDetails(p1, p2, p3, p4);
            }

            return false;
        });

        function loadFinanceDetails(product_type, cost_of_goods, deposit_percentage, deposit_amount) {

            var my_fd_obj = new FinanceDetails(product_type, cost_of_goods, deposit_percentage, deposit_amount);
            
        //  jQuery("#rate_of_interest").html(my_fd_obj.rate_of_interest+"<br/><span class='subline'>"+my_fd_obj.rate_of_interest+" APR representative</span>");
            jQuery("#rate_of_interest_frm").html(my_fd_obj.rate_of_interest+"<br/><span class='subline'>"+my_fd_obj.rate_of_interest+" APR representative</span>");
            jQuery("#product_name").html(my_fd_obj.p_name);
            jQuery("#finance_term").html(my_fd_obj.term+" monthly instalments");
            jQuery("#cost_per_month").html("&#163;"+my_fd_obj.m_inst.toFixed(2));
            jQuery("#cost_of_goods").html("&#163;"+my_fd_obj.goods_val);
            jQuery("#deposit_percentage").html("&#163;"+my_fd_obj.d_pc);
            jQuery("#deposit_amount").html("&#163;"+my_fd_obj.d_amount);
            jQuery("#apr").html("&#163;"+my_fd_obj.apr);
            jQuery("#monthly_repayment").html("&#163;"+my_fd_obj.l_repay);
            jQuery("#total").html("&#163;"+my_fd_obj.total);
            jQuery("#credit_amount").html("&#163;"+my_fd_obj.l_amount);
            jQuery("#loan_cost").html("&#163;"+my_fd_obj.l_cost);
            jQuery("#loan_true_cost").html("&#163;"+my_fd_obj.l_truecost);
        }

    });

    
</script>