<?php
$collect = $this->methodblock();
?>
<style>
#map_wrapper {
    height: 400px;
}

#map_canvas {
    width: 100%;
    height: 100%;
}


/* CMS contact page 5-2-2016*/
.cms-contact-us .contact-title{
	background:#dd2235;
}
.cms-contact-us .contact-title h2{
	text-align:center;
	color:#fff;
	padding:10px;
}
.cont-title{
	font-weight:bold;
	font-size:16px;
	color:#000;
	padding-bottom:10px;
}
.cms-contact-us .right_name.col-md-10, .cms-contact-us .right_more_info.col-md-2{
	/*padding:2px 0;*/
}
.cms-contact-us .right_name.col-md-10{
	border-top:1px solid #ddd;
	border-bottom:1px solid #ddd;
	padding: 7px 0;
}
.cms-contact-us .right_more_info.col-md-2{
	padding: 0;
}
.right_title.cont-title{
	padding:0;
	margin-top:2em;
	margin-bottom: 10px;
}
.contacts_container .btn{
	color: #fff;
	background:#dd2235;
	box-shadow:none;
	text-shadow:none;
	display: inline-block;
	margin-bottom: 0;
	font-weight: normal;
	text-align: center;
	vertical-align: middle;
	cursor: pointer;
	background-image: none;
	border: 1px solid transparent;
	white-space: nowrap;
	padding: 6px 12px;
	font-size: 14px;
	line-height: 1.42857143;
	border-radius: 4px;
}
.contacts_container .btn:hover{
	background:#f32338;
}
.contacts_container .right_name{
	font-size:16px;
	color:#000;
}
.cust_service_img img{
	width:75px;
	margin-top:3em;
	margin-bottom:1em;
}
.contact_us_now_img img{
	width:250px;
	position: relative;
	top: 82px;
}
.cms-contact-us #map_wrapper{
	height:650px;
	margin-bottom:0;
}
.cms-contact-us .form-inline .input-group > .form-control{
	height:30px;
	width:auto!important;
}
.cms-contact-us .input-group-addon {
    background: red none repeat scroll 0 0;
    border-radius: 2px;
    color: #fff;
    padding: 8px;
}
.cms-contact-us .input-group input, .cms-contact-us textarea {
    border:0;
	background:#f8f8f8;
	box-shadow:none;
	color:#999;
}
.cms-contact-us .input-group .fa {
    height: 30px;
    margin-bottom: 5px;
    width: 30px;
}
.cms-contact-us .input-group text-area {
    width: 100%;
}
.cms-contact-us .input-group button {
    background:#dd2235;
}
.cust_service_img strong {
    color: #000;
    font-size: 16px;
    position: relative;
    top: 55px;
}

.cust_service_img strong {
    color: #000;
    font-size: 16px;
    position: relative;
    top: 55px;
}
.contact_us_form {
    margin-top: 50px;
}
.contact_us_form .btn {
    float: right;
	margin-top: 10px;
}
.contact_us_form form {
    display: block;
}
.contact_us_form input[type="text"], .contact_us_form textarea {
    width: -webkit-calc(100% - 34px) !important;
    width: -moz-calc(100% - 34px) !important;
    width: -ms-calc(100% - 34px) !important;
    width: -o-calc(100% - 34px) !important;
    width: calc(100% - 34px) !important;
	display: inline-block;
}
.contact_us_form textarea
{
	height: 70px;
}
.contact_us_form .input-group-addon.fa.fa-comment {
    position: relative;
    top: -20px;
}
.cms-contact-us .main-container.col1-layout, .cms-contact-us .main-container.col1-layout .col-main {
    padding-bottom: 0;
}
.cms-contact-us .main-container.col1-layout, .cms-contact-us .main-container.col1-layout .col-main {
    padding-bottom: 0;
}
.contact_us_form .form-group {
    margin-bottom: 0;
}

@media only screen and (min-width: 992px)
{
	.cms-contact-us .right_name.col-md-10{
		width: 80.333%;
	}	
	.right_stores_details_container > .right_container:first-child > .right_title.cont-title:first-child {
		margin-top: 5px;
	}
}

@media only screen and (max-width: 991px)
{
	.right_name_container .row {
		margin: auto;
	}	
}

@media only screen and (min-width: 992px) and (max-width: 1199px)
{
	.contact_us_now_img img
	{
		top: 98px;
	}
}

@media only screen and (min-width: 768px) and (max-width: 991px)
{
	.contact_us_now_img img
	{
		top: 70px;
	}
}
	
@media only screen and (max-width: 767px)
{
	.contact_us_now_img img
	{
		top: 0;
		display: block;
		margin: auto;
	}
}

/* End CMS contact page 5-2-2016*/

    </style>
   <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>locator/googleStore.js"></script> 
    <script>
function initialize() {
    var map;
    var mapOptions = {
    zoom: 10,
    center: new google.maps.LatLng(-25.363882, 131.044922),
  };
                  
    map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
    var cnt = 0;
	var markers = [];
	var icons   = [];
	var message = [];
        <?php
	    echo count($collect);
	     foreach($collect as $row){ 
if($row->status == 1){
		$string = ""; 
		$string = $row->state." ".$row->country;
	     ?> 
    markers[cnt] = ['<?php echo $string; ?>',<?php echo $row->lat?>,<?php echo $row->long?>];
    icons.push('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>storeLocator/<?php echo $row->custom_icon;?>');
    message.push('<table width="300px" height="" style="padding:10px;"><tr><td width="60%" valign="top" align="left"><table width="100%" height=""><tr><td valign="top" align="left"><h3><?php echo $row->store_name;?></h3></td></tr><tr><td valign="top" align="left"><p><?php echo $row->store_name;?><br><?php echo $row->address;?>,<br><?php echo $row->city;?>, <?php echo $row->state;?><br><?php echo $row->country;?>- <?php echo $row->zip_code;?></p></td> </tr></table></td> <td width="40%" valign="top" align="left"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>storeLocator/<?php echo $row->store_image;?>" align="left"></td></tr></table>');
cnt++;
      <?php } } ?>   
var bounds = new google.maps.LatLngBounds();
  map.fitBounds(bounds);
    for( i = 0; i < markers.length; i++ ) {
        var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
        bounds.extend(position);
        marker = new google.maps.Marker({
            position: position,
            map: map,
	    icon:icons[i]
        });   
    
    marker.setTitle((i + 1).toString());
    attachSecretMessage(marker, i,message[i]);
  }
}
function attachSecretMessage(marker, num,messag) {
  var infowindow = new google.maps.InfoWindow({
    content: messag
  });

  google.maps.event.addListener(marker, 'click', function() {
    infowindow.open(marker.get('map'), marker);
  });
}
google.maps.event.addDomListener(window, 'load', initialize);
    </script>

<div class="contacts_container">
	<div class="row">
		<div class="col-md-6">
			<div id="map_wrapper" style="background-color:#ffffff;padding:5px;border-radius:10px 10px 10px 10px;">
				<div id="map_canvas" class="mapping"></div>
			</div>
		</div>
	<div class="col-md-6">
		<div class="right_stores_details_container">
			<div class="right_container">
				<div class="right_title cont-title"><?php echo $this->__("Stores"); ?></div>
				<div class="right_names">
					<div class="right_name_container">
						<div class="row">
							<div class="right_name col-md-10 col-sm-10 col-xs-9">
								<?php echo $this->__("N.ireland"); ?>
							</div>
							<div class="right_more_info col-md-2 col-sm-2 col-xs-3 text-right">
								<a class="more_info_button btn btn-primary" href="<?php echo Mage::getBaseUrl() . "click-collect-service-n-ireland/"; ?>" title="More Info about N.Ireland Store"><?php echo $this->__("More Info"); ?></a>
							</div>
						</div>
					</div>
					<div class="right_name_container">
						<div class="row">
							<div class="right_name col-md-10 col-sm-10 col-xs-9">
								<?php echo $this->__("West Sussex"); ?>
							</div>
							<div class="right_more_info col-md-2 col-sm-2 col-xs-3 text-right">
								<a class="more_info_button btn btn-primary" href="<?php echo Mage::getBaseUrl() . "click-collect-service-west-sussex/"; ?>" title="More Info about West Sussex Store"><?php echo $this->__("More Info"); ?></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="right_container">
				<div class="right_title cont-title"><?php echo $this->__("Tech Support"); ?></div>
				<div class="right_names">
					<div class="right_name_container">
						<div class="row">
							<div class="right_name col-md-10 col-sm-10 col-xs-9">
								<?php echo $this->__("Warwick"); ?>
							</div>
							<div class="right_more_info col-md-2 col-sm-2 col-xs-3 text-right">
								<a class="more_info_button btn btn-primary" href="<?php echo Mage::getBaseUrl() . "warwick-tech-support/"; ?>" title="More Info about Warwick Tech Support"><?php echo $this->__("More Info"); ?></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="right_container">
				<div class="right_names">
					<div class="right_name_container">
							<div class="row">
								<div class="right_name col-md-10 col-sm-10 col-xs-9">
									<?php echo $this->__("London"); ?>
								</div>
								<div class="right_more_info col-md-2 col-sm-2 col-xs-3 text-right">
									<a class="more_info_button btn btn-primary" href="<?php echo Mage::getBaseUrl() . "24-7-customer-service/"; ?>" title="More Info about London Customer Services"><?php echo $this->__("More Info"); ?></a>
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
	</div> <!--Col-md-6-->
	</div> <!--.row-->

</div>
