<style>

/*.store-info-content {
    border: 2px solid #000;
    padding: 15px;
	box-shadow: 0 0 3px 2px #cbcbcb inset;
}*/

.store-info-header {
    background-color: #df1e2d;
}
.store-info-header h2 {
    background-color: #df1e2d;
    color: #fff;
    text-align: center;
	padding: 10px;
}


/*.store-info-title {
    border-color: #cbcbcb;
    border-style: solid;
    border-width: 1px 0;
    color: #000;
    font-size: 32px;
    margin: 15px auto 30px;
    padding: 5px 0;
    text-align: center;
}*/

.store-info-details {
    color: #000;
}
.store-info-location-title, .store-info-hours-title, .store-social-title {
    font-size: 18px;
    margin-bottom: 5px;
}
.store-info-contact {
    color: #ff0035;
    margin: 10px auto;
}
.store-info-open-hours {
    margin-bottom: 10px;
}
.store-social-icons .social-icons {
    float: none;
}


.store-social-icons .social-icons {
    float: none;
}
.store-social-container {
    margin-bottom: 20px;
}
.store-info-content img.img-responsive {
    margin: auto auto 20px;
}
.store-info-gallery .img-responsive {
    height: 215px;
    max-width: 215px;
}


.cms-24-7-customer-service .store-info-gallery .store-info-image {
    width: 100%;
}
.cms-24-7-customer-service .store-info-gallery .store-info-image img {
    height: auto;
    max-width: 713px;
    width: 100%;
}


@media only screen and (min-width: 992px)
{
	.store-info-map .img-responsive {
		height: 475px;
		width: 100%;
	}
}

</style>