<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.4.11
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        $this->markAsShowed();
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
    <section class="featured-slider related row">
        <h3><?php echo $this->htmlEscape($this->getData('name')) ?></h3>
        <ol class="clearfix">
            <?php foreach($collection as $_item): ?>
                <li class="item">
                    <div class="item-content">
                        <div class="item-images">
                            <a href="<?php echo $_item->getProductUrl() ?>"><img class="item-image spinner" src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(430,404) ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>"></a>
                            <div class="product-label-placeholder" data-productid="<?php echo $_item->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel"></div>
                        </div>
                        <div class="item-info">
                            <h6 class="item-title"><a href="<?php echo $_item->getProductUrl() ?>" class="truncate"  title="<?php echo $this->escapeHtml($_item->getName()) ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h6>
                            <?php if($_item->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_item, 'short', false) ?>
                            <?php endif; ?>
                            <?php echo $abstractBlock->getPriceHtml($_item, true, '-related') ?>
                        </div>
                        <div class="actions clearfix">
                            <?php if(!$_item->canConfigure() && $_item->isSaleable() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', Mage::app()->getStore())): ?>
                                <button class="btn-cart" title="<?php echo $this->__('Add to Cart') ?>" type="button" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_item) ?>')"><?php echo $this->__('Add to Cart') ?></button>
                            <?php elseif($_item->getStockItem() && $_item->getStockItem()->getIsInStock()): ?>
                                <button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart preview" onclick="setLocation('<?php echo $_item->getProductUrl() ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php if($this->helper('wishlist')->isAllow()): ?>
                                    <li><a class="link-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_item); ?>
                                <?php if($_compareUrl): ?>
                                    <li><a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ol>
    </section>
<?php endif;?>